title: Manu Gupta
tagline: Reproductions of machine learning papers
description: Machine learning paper reproductions.
url: https://mgupta8143.github.io
github_username: mgupta8143

collections:
  reproductions:
    output: true
    permalink: /reproductions/:name/

defaults:
  - scope: { path: "", type: reproductions }
    values: { layout: reproduction }

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude: [README.md, Gemfile, Gemfile.lock, vendor]
